//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A megadott motorszámmal már regisztráltak járművet!.
        /// </summary>
        internal static string EngineNumberDoesNotExist {
            get {
                return ResourceManager.GetString("EngineNumberDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás motorszám formátum! Két betű, majd tizenkét szám. Pl: AB123456789000.
        /// </summary>
        internal static string InvalidEngineNumber {
            get {
                return ResourceManager.GetString("InvalidEngineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A keresztvén csak betűkből állhat..
        /// </summary>
        internal static string InvalidFirstNameChar {
            get {
                return ResourceManager.GetString("InvalidFirstNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A keresztnév túl sok karakterből áll..
        /// </summary>
        internal static string InvalidFirstNameLength {
            get {
                return ResourceManager.GetString("InvalidFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A keresztnév nem lehet null vagy üres!.
        /// </summary>
        internal static string InvalidFirstNameNull {
            get {
                return ResourceManager.GetString("InvalidFirstNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vezetéknév csak betűkből állhat..
        /// </summary>
        internal static string InvalidLastNameChar {
            get {
                return ResourceManager.GetString("InvalidLastNameChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vezetéknév túl sok karakterből áll..
        /// </summary>
        internal static string InvalidLastNameLength {
            get {
                return ResourceManager.GetString("InvalidLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A vezetéknév nem lehet null vagy üres!.
        /// </summary>
        internal static string InvalidLastNameNull {
            get {
                return ResourceManager.GetString("InvalidLastNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás irányítószám formátum..
        /// </summary>
        internal static string InvalidPostalCode {
            get {
                return ResourceManager.GetString("InvalidPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás rendszám formátum. Példa: AABB001.
        /// </summary>
        internal static string InvalidRegistrationNumber {
            get {
                return ResourceManager.GetString("InvalidRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem létező jármű kategória! Válassz az alábbiak közül: M1, N1, N2, N3, O1, O2, O3, L3E.
        /// </summary>
        internal static string InvalidVehicleType {
            get {
                return ResourceManager.GetString("InvalidVehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rendszám még nem létezik..
        /// </summary>
        internal static string RegistrationNumberDoesNotExist {
            get {
                return ResourceManager.GetString("RegistrationNumberDoesNotExist", resourceCulture);
            }
        }
    }
}
